document.write("Number对象p122");
br();
var originNumber = 10.23456;
var msg = '<h2>originNumber</h2><p>' + originNumber + '</p>';
msg += '<h2>四舍五入toFixed()</h2><p>' + originNumber.toFixed(3) + '</p>';
msg += '<h2>得到数字指定位数toPrecision()</h2><p>' + originNumber.toPrecision(3) + '</p>';
document.write(msg);
br();
var n = new Number(123.054);
document.write("123.054:" + n);
br();
var s = new String('fds');
document.write("变量只能用var定义：" + s);
br();
var a, b, c;
document.write("Math.PI:" + Math.PI);
br();
document.write("离它最近的整数Math.round(1.49):" + Math.round(1.49));
br();
document.write("离它最近的整数Math.round(1.50):" + Math.round(1.50));
br();
document.write("开平方根Math.sqrt(1.23):" + Math.sqrt(1.23));
br();
document.write("离它最近的整数并大于它Math.ceil(1.23):" + Math.ceil(1.23));
br();
document.write("离它最近的整数并大于它Math.ceil(1.00):" + Math.ceil(1.00));
br();
document.write("离它最近的整数并小于它Math.floor(1.23):" + Math.floor(1.23));
br();
document.write("离它最近的整数并小于它Math.floor(1.00):" + Math.floor(1.00));
br();
document.write("随机[0,1)Math.random() * 100:" + Math.random() * 100);
br();
document.write("随机[0,1)Math.floor(Math.random() * 100):" + Math.floor(Math.random() * 100));
br();
document.write("使用Math.floor()比使用Math.round()产生的随机数更加准确，因为后者1和100出现的几率是其他数字的一半");
